spring.data.mongodb.uri=${DATASOURCE_URL}

server.port=${PORT:8080}
server.servlet.context-path=${APP_CONTEXT_PATH}

#spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=${CLERK_USER}
clerk.jwks-url=${CLERK_JWQS_URL}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

#file upload configuration
spring.servlet.multipart.max-file-size=${FILE_SIZE}
spring.servlet.multipart.max-request-size=${REQUEST_SIZE}

#razorpay configuration
razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_SECRET}