spring.data.mongodb.uri=mongodb+srv://atreus396_db_user:n4tp5BLzeU3t37Yp@cluster0.losbdb7.mongodb.net/SkyLink

server.servlet.context-path=/api/v1.0

#spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://cosmic-stud-77.clerk.accounts.dev
clerk.jwks-url=https://cosmic-stud-77.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=HzYW1wHbW/SQCZlIyVJgftmZy18aDV33

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

#razorpay configuration
razorpay.key.id=rzp_test_RUWUfHRXvuBkZu
razorpay.key.secret=f61cq8KDkshGrCOoLjr6BYYX